name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'publish'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: CrossOS

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Run Restore-Dependencies script
      run: pwsh -Command "Start-Process pwsh -ArgumentList '-File','$PWD/restore/Restore-Dependencies.ps1','-Verbose' -WorkingDirectory $PWD/restore"

    - name: Run Build-Release
      run: pwsh scripts/Build-Release.ps1 -Verbose

    - name: Upload test artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-release
        path: release/*.zip
