name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: CrossOS

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Set restore directory
      run: cd restore
      
    - name: Run run Restore-Dependencies script
      run: pwsh Restore-Dependencies.ps1 -Verbose

    - name: Go back to build directory
      run: cd ..
    - name: Run Build-Release
      run: pwsh scripts/Build-Release.ps1 -Verbose

    - name: Upload test artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-release
        path: release/*.zip
